### ISSUE TITLE
Query parameters with '//' in them get collapsed to '/'

### ISSUE THREAD

**Issue by drone1** [VeliovGroup/flow-router#102]
Google OAuth redirects to web apps with the _scope_ included on the query string. 

Example URL:

http://www.test.com/oauth-redirect?code=xxx&scope=https://www.googleapis.com/auth/gmail.modify

However, this line corrupts the query string, collapsing ``https://`` to ``https:/``:

https://github.com/veliovgroup/flow-router/blob/6961ad112968c8ed2c6a00e22ef9ce6581e1d4ac/client/router.js#L478

**Comment by dr-dimitru** [comment]
@drone1 I'm sure there was a reason for this `.replace()` call. Do you want to send a PR providing an option to disable this behavior?

**Comment by drone1** [comment]
probably to remove erroneous double-slashes from the url. which may still
be needed. but perhaps not for the query string.

**Comment by dr-dimitru** [comment]
@drone1 then we would need to exclude `https?:\/\/` from this replacement

**Comment by drone1** [comment]
Sadly I don't have time to submit a PR, but hopefully this code can get someone else started:

```
const pathParts = path.split('?')
let fixedPath = pathParts[0].replace(/\/\/+/g, '/')
if (pathParts.length > 1) {
   fixedPath += `?${pathParts[1]}`
}
original.call(self, fixedPath, state, dispatch, push); 
```
