### ISSUE TITLE
Router.group prefix in type definition

### ISSUE THREAD

**Issue by taylorshephard** [VeliovGroup/flow-router#105]
### I'm having an issue:
According to [docs here](https://github.com/veliovgroup/flow-router/blob/master/docs/full.md), the `prefix` option is optional for `Router.group` but required in the type definition
 
  - `ostrio:flow-router-extra@3.9.0`
  - `METEOR@2.12`
```js
FlowRouter.group({
  name: 'fooGroup',
  triggersEnter: [],
});
```
error:
```
Parameter 'context' implicitly has an 'any' type, but a better type may be inferred from usage.ts(7044)
Argument of type '{ name: string; triggersEnter: ((context: any, redirect: any) => void)[]; }' is not assignable to parameter of type '{ [key: string]: any; name: string; prefix: string; }'.
  Property 'prefix' is missing in type '{ name: string; triggersEnter: ((context: any, redirect: any) => void)[]; }' but required in type '{ [key: string]: any; name: string; prefix: string; }'.ts(2345)
types.d.ts(59, 38): 'prefix' is declared here.
```

### I have a suggestion:
make a change [here](https://github.com/veliovgroup/flow-router/blob/b3b90c97d208b4afe44626b8982d8a414f246e2c/types.d.ts#L59)
 ```ts
group: (options: { name: string; prefix?: string; [key: string]: any }) => any;
```

**Comment by dr-dimitru** [comment]
Hello @taylorshephard 👋
Thank you for the suggestion, going to add it in the upcoming release

**Comment by dr-dimitru** [comment]
Solved in the latest release.
Feel free to reopen it in case if the issue is still persists on your end.
