### ISSUE TITLE
Using fetch instead of the deprecated http package

### ISSUE THREAD

**Issue by dokithonon** [VeliovGroup/flow-router#107]
Hello,
As mentioned here : https://docs.meteor.com/api/http the http package is deprecated and they advise to use the fetch package.

This is used apparently on tests only.

This is even more important when moving to Meteor v3 as the http packages gets downgraded to a very old version when moving to Meteor version 3

This is the same for ostrio:cookies

**Comment by dr-dimitru** [comment]
Hello @dokithonon ,

Thank you for reporting this one. I see where `http` package used in test by `ostrio:flow-router-extra`, but can not find its usage in `ostrio:cookies` package, please advise

**Comment by dokithonon** [comment]
You are right. As flow router use cookie I thought it was in flow router. Thanks for your work.
