### ISSUE TITLE
[SOLVED] Conflict: Constraint blaze@2.1.8 is not satisfied by blaze 3.0.0-alpha300.17.

### ISSUE THREAD

**Issue by dokithonon** [VeliovGroup/flow-router#109]
Updating to Meteor 3.0 lead to this : 

`=> Errors while upgrading packages:           
                                              
While selecting package versions:
error: Conflict: Constraint blaze@2.1.8 is not satisfied by blaze 3.0.0-alpha300.17.
Constraints on package "blaze":
* blaze@3.0.0-alpha300.17 <- spacebars 2.0.0-alpha300.17 <- rationalk:bpm 0.0.0
* blaze@3.0.0-alpha300.17 <- templating-runtime 2.0.0-alpha300.17 <- templating 1.4.4-alpha300.13 <- aldeed:tabular 2.1.2 <- rationalk:core 0.0.0
* blaze@3.0.0-alpha300.17 <- templating-runtime 2.0.0-alpha300.17 <- templating 1.4.4-alpha300.13 <- blaze-html-templates 3.0.0-alpha300.17
* blaze@3.0.0-alpha300.17 <- blaze-html-templates 3.0.0-alpha300.17
* blaze@3.0.0-alpha300.17 <- accounts-base 3.0.0-beta300.7
* blaze@2.1.8 <- ostrio:flow-router-extra 3.10.1`

I was able to solve this by manually editing this line : 

  api.use(['templating', 'blaze@3.0.0-alpha300.17'], 'client', { weak: true });

I don't know if this is correct. Can you advise ?
Thanks

**Comment by p-wieser** [comment]
Same here when trying to `meteor add ostrio:flow-router-extra@3.10.1` for a freshly created meteor app `meteor create app --blaze --release meteor-3.0-rc.2`.
But I also had to update the typescript dependency.
I do not understand how to submit a PR here as I am redirected to kadirahq original repository :(
So the proposed patch below :
```
From 8ec6308216a025892c937dfd8b899893cd688f11 Mon Sep 17 00:00:00 2001
From: Pierre Wieser <p.wieser@trychlos.org>
Date: Wed, 22 May 2024 15:53:53 +0200
Subject: [PATCH] Update blaze and typescript dependencies to be
 Meteor-3.0-rc.2 compatible

---
 package.js | 4 ++--
 1 file changed, 2 insertions(+), 2 deletions(-)

diff --git a/package.js b/package.js
index 8bcbaa1..c48bf7d 100644
--- a/package.js
+++ b/package.js
@@ -9,8 +9,8 @@ Package.onUse((api) => {
   api.versionsFrom(['1.4', '3.0-beta.0']);
   api.use(['modules', 'ecmascript', 'promise', 'tracker', 'reactive-dict', 'reactive-var', 'ejson', 'check'], ['client', 'server']);
 
-  api.use(['zodern:types@1.0.13', 'typescript'], ['client', 'server'], { weak: true });
-  api.use(['templating', 'blaze'], 'client', { weak: true });
+  api.use(['zodern:types@1.0.13', 'typescript@5.4.3-rc300.2'], ['client', 'server'], { weak: true });
+  api.use(['templating', 'blaze@3.0.0-alpha300.17'], 'client', { weak: true });
   api.mainModule('client/_init.js', 'client');
   api.mainModule('server/_init.js', 'server');
 });
-- 
2.45.1
```

**Comment by dr-dimitru** [comment]
@p-wieser please update to [`@3.11.0-rc300.0`](https://packosphere.com/ostrio/flow-router-extra/3.11.0-rc300.0) and let me know if it works

**Comment by dokithonon** [comment]
Hello @dr-dimitru I have tried to update to 3.11.0-rc300.0 but I still have the problem with Blaze : 

```
=> Errors prevented startup:                  
   
   While selecting package versions:
   error: Conflict: Constraint blaze@2.1.8 is not satisfied by blaze 3.0.0-alpha300.17.
   Constraints on package "blaze":
   * blaze@3.0.0-alpha300.17 <- spacebars 2.0.0-alpha300.17 <- rationalk:bpm 0.0.0
   * blaze@3.0.0-alpha300.17 <- templating-runtime 2.0.0-alpha300.17 <- templating 1.4.4-alpha300.13 <-
   aldeed:tabular 2.1.2 <- rationalk:core 0.0.0
   * blaze@3.0.0-alpha300.17 <- templating-runtime 2.0.0-alpha300.17 <- templating 1.4.4-alpha300.13 <-
   blaze-html-templates 3.0.0-alpha300.17
   * blaze@3.0.0-alpha300.17 <- blaze-html-templates 3.0.0-alpha300.17
   * blaze@3.0.0-alpha300.17 <- accounts-base 3.0.0-rc300.2
   * blaze@2.1.8 <- ostrio:flow-router-extra 3.11.0-rc300.0
   * blaze@2.9.0 || 3.0.0-alpha300.17 <- alanning:roles 4.0.0-alpha.2
   
=> Your application has errors. Waiting for file change.
```

My fix above was working. I am not able to see the source code of this version of the package, can you give us the link so that I can check the Blaze dependency ?

**Comment by dr-dimitru** [comment]
@dokithonon please try [`3.11.0-rc300.1`](https://packosphere.com/ostrio/flow-router-extra/3.11.0-rc300.1)

**Comment by p-wieser** [comment]
Here, @3.11.0-rc300.0 works like a charm. Thanks.

**Comment by dokithonon** [comment]
@dr-dimitru @3.11.0-rc300.1 works perfectly . Great job ! Thanks.

**Comment by dr-dimitru** [comment]
@dokithonon thank you for reporting this one
