### ISSUE TITLE
[Feature] Global waitOn hook

### ISSUE THREAD

**Issue by WayneUong** [VeliovGroup/flow-router#11]
Like this?

```js
FlowRouter.globals.push({
  waitOn() {
    return [import(/*...*/)];
  }
});
```

**Comment by dr-dimitru** [comment]
@WayneUong ,

Thank you for suggestion. My guess same should also apply to the route groups, right?

**Comment by WayneUong** [comment]
@dr-dimitru Yeah on the route group level would be great too. Btw, I'm transitioning from the old FlowRouter and the global namespace seems to be gone. Right now I have to do a hack:
```
import {FlowRouter as flowRouter} from '...';
FlowRouter = flowRouter;
```

Is there a better way? We have too many unimported FlowRouter's around. Thank you.

**Comment by dr-dimitru** [comment]
> Btw, I'm transitioning from the old 

Great

> the global namespace seems to be gone

Yes, thanks to Meteor new principles

> Is there a better way?

```js
// The best way to make sure you follow new Meteor principles
import { FlowRouter } from 'meteor/ostrio:flow-router-extra';

// Expose FlowRouter to the global will work too
// This will work on both Client and Server
// Best if this done in the /lib/
import {FlowRouter as flowRouter} from 'meteor/ostrio:flow-router-extra';
this.FlowRouter = global.FlowRouter = flowRouter;
```

**Comment by WayneUong** [comment]
Thanks @dr-dimitru very nice package with lots of good features.

**Comment by dr-dimitru** [comment]
@WayneUong thank you for feedback, this means a lot for me, and feature suggestion, it will arrive on next release.

Please, support this project by:
 - Star on [GitHub](https://github.com/VeliovGroup/flow-router)
 - Star on [Atmosphere](https://atmospherejs.com/ostrio/flow-router-extra)

**Comment by valorloff** [comment]
Hi @dr-dimitru!
 
layout.js:
```
import './layout.html';
import './main.html';
import './main.js';
import '/imports/ui/service.js';
```
routes.js (don't works):
```
FlowRouter.route('/cart',{
    name: 'cartItems',
    loadingTemplate: 'loading',
    waitOn() {
      import('/imports/ui/cart/layout.js');
    },
```
but
```
FlowRouter.route('/cart',{
    name: 'cartItems',
    loadingTemplate: 'loading',
    waitOn() {
    return [import('/imports/ui/cart/layout.html'),
      import('/imports/ui/cart/main.html'),
      import('/imports/ui/cart/main.js'),
      import('/imports/ui/service.js')]
      // import('/imports/ui/cart/layout.js');
    },
```
works! 
when bunch files is large, how improve this?

**Comment by dr-dimitru** [comment]
Hello @valorloff ,

You're missing `return` key word here:
```diff
FlowRouter.route('/cart',{
    name: 'cartItems',
    loadingTemplate: 'loading',
    waitOn() {
+      return  import('/imports/ui/cart/layout.js');
-      import('/imports/ui/cart/layout.js');
    },
```

**Comment by valorloff** [comment]
sorry, ...shame :)

**Comment by dr-dimitru** [comment]
@valorloff solved?

**Comment by valorloff** [comment]
sure! It's a stupid mistake, 
thanks!
per route DynImport works nice

**Comment by dr-dimitru** [comment]
Great, no worries. Thank you for support and the choice )

**Comment by btbjosh** [comment]
+1 for Group route dynamic imports. I have a system admin panel that I would prefer to import all the system stuff in once there and not in each route :)

Keep up the great work. These are nice additions to FlowRouter!

**Comment by dr-dimitru** [comment]
Hello everyone,

Thank you for reminding me about this feature.
It's implemented in [v.3.2.0](https://github.com/VeliovGroup/flow-router/releases/tag/3.2.0), please upgrade.

Feel free to close this issue if [v.3.2.0](https://github.com/VeliovGroup/flow-router/releases/tag/3.2.0) solved it.
