### ISSUE TITLE
Use fetch instead of http

### ISSUE THREAD

**Issue by dokithonon** [VeliovGroup/flow-router#110]
Hello,
The package uses `http` (in tests). Will it be possible to use the `fetch` package instead ?
`http` is deprecated in favor of `fetch` : https://docs.meteor.com/api/http

**Comment by dokithonon** [comment]
@dr-dimitru does your new package ostrio:flow-router-extra@3.11.0-rc300.1 still use http ? or you have migrated to fetch ? thanks. If you have migrated to fetch you can close the issue.

**Comment by dr-dimitru** [comment]
@dokithonon yes! I only patched dependencies and ran tests
