### ISSUE TITLE
[METEOR@3.0-rc.0] Exception in setInterval callback

### ISSUE THREAD

**Issue by ddaydd** [VeliovGroup/flow-router#111]
I have this error in the console, am I the only one? have you already tried flow router with meteor 3?

Exception in setInterval callback: TypeError: subscription.ready is not a function at Route.checkSubscriptions
- flow-router-extra@2.11.0
- METEOR@3.0-rc.0

Edit : sorry, I have a package that prevents me from updating flow-router-extra and I don't know which one yet...

**Comment by dr-dimitru** [comment]
Hello @ddaydd, 
why it isn't planned?

**Comment by ddaydd** [comment]
sorry, I haven't managed to update the latest version of flow-router at the moment, and as I didn't know if the error was still relevant, I closed the topic...

**Comment by dr-dimitru** [comment]
@ddaydd do you mean it was solved after you upgraded?

**Comment by ddaydd** [comment]
no, I didn't manage to update, I don't know why a package is blocking me from updating and even by doing a meteor list -tree I can't find what this package is...

**Comment by dr-dimitru** [comment]
let me know if I can help

**Comment by ddaydd** [comment]
thanks, I will try to update first, to be continued :)

**Comment by ddaydd** [comment]
did you manage to install flow router on the latest version of METEOR@3.0-rc.0 with blaze ?
I have these errors on a new application

=> Errors prevented startup:

   While selecting package versions:
   error: Conflict: Constraint typescript@4.9.5-beta300.0 is not satisfied by typescript 5.4.3-rc300.0.
   Constraints on package "typescript":
   * typescript@5.4.3-rc300.0 <- top level
   * typescript@~5.4.3-rc300.0 <- top level
   * typescript@5.4.3-rc300.0 <- logging 1.3.3-rc300.0 <- mongo 2.0.0-rc300.0
   * typescript@4.9.5-beta300.0 <- ostrio:flow-router-extra 3.10.1

   Conflict: Constraint blaze@2.1.8 is not satisfied by blaze 3.0.0-alpha300.17.
   Constraints on package "blaze":
   * blaze@3.0.0-alpha300.17 <- launch-screen 1.3.1-rc300.0 <- mobile-experience 1.1.1-rc300.0
   * blaze@3.0.0-alpha300.17 <- blaze-html-templates 3.0.0-alpha300.17
   * blaze@3.0.0-alpha300.17 <- spacebars 2.0.0-alpha300.17 <- templating-runtime 2.0.0-alpha300.17 <- blaze-hot
   2.0.0-alpha300.17
   * blaze@3.0.0-alpha300.17 <- templating-runtime 2.0.0-alpha300.17 <- blaze-hot 2.0.0-alpha300.17
   * blaze@3.0.0-alpha300.17 <- blaze-hot 2.0.0-alpha300.17
   * blaze@2.1.8 <- ostrio:flow-router-extra 3.10.1

**Comment by ddaydd** [comment]
Hi, it's works.

I changed api.versionsFrom(['1.4', '3.0-beta.0']); by api.versionsFrom(['3.0-rc.0']);
and the latest version does not have the subscription bug

Thank you for motivating me to go further :)

**Comment by dr-dimitru** [comment]
@ddaydd 

> I changed api.versionsFrom(['1.4', '3.0-beta.0']); by api.versionsFrom(['3.0-rc.0']);

Changed in what package?

**Comment by ddaydd** [comment]
in ostrio:flow-router-extra that I downloaded  :-p

**Comment by acemtp** [comment]
I had to clone the package just to add "3.0-rc.0" in a file.

Why this change is not in the main branch and the package released to be compatible with meteor 3?

**Comment by dr-dimitru** [comment]
@acemtp would you try [`v3.11.0-rc300.1`](https://packosphere.com/ostrio/flow-router-extra/3.11.0-rc300.1) it should definitely work. What version have you installed?

**Comment by acemtp** [comment]
Damned, it was not in the release https://github.com/veliovgroup/flow-router/releases

I didn't know this version existed, thanks, I'll use it!

**Comment by dr-dimitru** [comment]
@acemtp it's pre-release, so I don't log it
