### ISSUE TITLE
Maybe compatibility issue

### ISSUE THREAD

**Issue by danbalarin** [VeliovGroup/flow-router#12]
Hello guys,

today I tried this package, due to dynamic imports in routes. But after some setup, some routes are working, some not. Working routes are still throwing `There is no route for the path:` error, but everything else is okay, rendered and stuff. Non-working routes are those which use `kadirahq:blaze-layout` dynamic template. Is there any possibility to get this working or use yield included in this package in similiar way (like multiple yields on template and naming them)?

**Comment by dr-dimitru** [comment]
Hello @Kenny11CZ ,

Everything should work as before. Make sure defined routes is __statically__ imported in the app bundle.

Speaking of the difference `blaze-layout` and built in `.render()`.
Yes, `yield` is required for `.render()`, but can only one per template, but you can use it as before with `blaze-layout` if you need dynamic regions:
```html
<!-- /imports/client/layout.html -->
<template name="layout">
  {{> yield}}
</template>
```
```html
<!-- /imports/client/main.html -->
<template name="main">
  <aside>
    {{> Template.dynamic template=sidebar}}
  </aside>
  <main>
    {{> Template.dynamic template=content}}
  </main>
  <footer>
    {{> Template.dynamic template=footer}}
  </footer>
</template>
```
```js
// /client/main.js
import '/imports/lib/routes.js';
import '/imports/client/layout.html';
import '/imports/client/main.html';
```
```js
// /imports/client/index.js
import { Template } from 'meteor/templating';
import '/imports/client/sidebarTemplate.html';
import '/imports/client/contentTemplate.html';
import '/imports/client/footerTemplate.html';

Template.index.helpers({/*...*/});
```
```js
// /imports/lib/routes.js
import { FlowRouter }  from 'meteor/ostrio:flow-router-extra';

FlowRouter.route('/', {
  name: 'index',
  waitOn() {
    return import('/imports/client/index.js');
  },
  action() {
    this.render('layout', 'main', {
      sidebar: 'sidebarTemplate',
      content: 'contentTemplate',
      footer: 'footerTemplate',
    });
  }
});
```

To me it's much more complex than have a few different layouts with all kind of footers and sidebars you need. Of course selection between those two concepts should be made with better fit for project needs in mind.

**Comment by danbalarin** [comment]
I am so sorry for bothering you, but I think it's my stupidity. I forgot to remove old `kadira:flow-router` so, that solves missing route even when rendered and `blaze-layout` might wanted to use that package to, so it might solve the second problem. But I've come to conclusion that single yield is so far sufficient, maybe later I will install again `blaze-layout`.
One last question, can I pass something imported in `waitOn()` to data field in `render`? Like the example you have provided me, but instead of sidebar, content and footer being loaded statically, load them dynamically?
Again, I am sorry for taking your time, but I am pretty sure, some one (including me) will find it helpful.

**Comment by dr-dimitru** [comment]
I suggest to look at [the docs](https://github.com/VeliovGroup/flow-router#waiton-hook).

Generally `.waitOn()` not supposed to return data, use `.data()` hook which will be triggered once everything in `.waitOn()` is ready.

If you want to use module returned from `import` in `.waitOn()` it's safe to use upper-scope variable as route has only one state per time.

Let me know if there is any further questions.

**Comment by dr-dimitru** [comment]
Hello @Kenny11CZ ,

Is this one solved?

**Comment by danbalarin** [comment]
Okey, that's all. Thanks a lot and now you can close it.

**Comment by dr-dimitru** [comment]
Please, support this project by:
 - Star on [GitHub](https://github.com/VeliovGroup/flow-router)
 - Star on [Atmosphere](https://atmospherejs.com/ostrio/flow-router-extra)
 - Check [other packages](https://github.com/search?o=desc&q=topic%3Ameteor-package+org%3AVeliovGroup&s=stars&type=Repositories) we have made
