### ISSUE TITLE
Dynamics imports and redirects

### ISSUE THREAD

**Issue by ch-lukas** [VeliovGroup/flow-router#13]
Starting using Meteor 1.5 and this router to be able to get most out of dynamic imports and everything is working well... almost. Any suggestions?

When I redirect (e.g. if user is already logged-in, redirect from / to dashboard) I get a 'no such template' error and then even with the error the page loads up correctly.

Some background :
  - I'm reading all dashboard / admin routes from a DB, so have to use FlowRouter.wait() / FlowRouter.initialize()
  - '/' route is hard coded in js route file example included below
  - Using waitOn() and return import('pageName') for all routes

Tried these 2 options, but don't work

```js
Open.route('/', {
	name: 'landingPage',
	triggersEnter: [function () {
		if (Meteor.userId()) {
                        // return import(' ....  eg dashboardPage');
			FlowRouter.go('/dashboard');
		}
	}],
	waitOn() {
		return import('/imports/ui/pages/landing');
	},
	action() {
		this.render('landingLayout', 'landingPage');
	}
});
```

Alternative,

```js
Open.route('/', {
	name: 'landingPage',
	waitOn() {
		if (Meteor.userId()) {
			return import(' ....  eg dashboardPage');
		} else {
			return import('/imports/ui/pages/landing');
		}
	},
	action() {
		if (Meteor.userId()) {
			FlowRouter.go('/dashboard');
		} else {
			this.render('landingLayout', 'landingPage');
		}
	}
});
```

**Comment by dr-dimitru** [comment]
Hello @chluke123 ,

What is `import(' ....  eg dashboardPage');` exactly? Is this something what generated dynamically?
Note: `import`, `import()` and `require()` can accept only string as argument, not a *variable* - __only string__. See [#8717](https://github.com/meteor/meteor/issues/8717) , [forum post](https://forums.meteor.com/t/how-to-use-import-require-with-dynamic-path/21955), [SO thread](https://stackoverflow.com/questions/40844484/how-to-import-by-dynamic-path-with-meteor)

**Comment by ch-lukas** [comment]
Hi @dr-dimitru,

That was just a placeholder value for illustration. A real life example is `return import('/imports/ui/pages/dashboard/navigation');`

In the navigation folder is an index that loads the templates etc.

Routes all works well, except in the instance of the initial root redirect.

At first glance, it seems as if the Flowrouter.go redirect is bypassing the hooks of the route you want to go to.

Cheers

**Comment by dr-dimitru** [comment]
Okay, then does it work this way?:
```js
Open.route('/', {
	name: 'landingPage',
	waitOn() {
		return import('/imports/ui/pages/landing');
	},
	action() {
		if (Meteor.userId()) {
			FlowRouter.go('/dashboard');
		} else {
			this.render('landingLayout', 'landingPage');
		}
	}
});

Open.route('/dashboard', {
	name: 'dashboard Page',
	waitOn() {
		return import(' ....  eg dashboardPage');
	},
	action() {
		this.render('dashboardLayout', 'dashboardPage');
	}
});
```

**Comment by ch-lukas** [comment]
It works - cheers! 

And so does my alternate example above... but I have been working on the code since then :).

The one constant is to watch out for the combination of triggersEnter / waitOn route imports / redirects.

Maybe a quick note in the docs about the limitations of using the triggersEnter hook might help.

Cheers, L

**Comment by dr-dimitru** [comment]
Well `triggersEnter` definitely isn't equal to `waitOn`.
I'm glad it's solved.

Feel free to reopen it in case if the issue still persists on your end.

Please, support this project by:
 - Star on [GitHub](https://github.com/VeliovGroup/flow-router)
 - Star on [Atmosphere](https://atmospherejs.com/ostrio/flow-router-extra)
 - Check [other packages](https://github.com/search?o=desc&q=topic%3Ameteor-package+org%3AVeliovGroup&s=stars&type=Repositories) we have made
