### ISSUE TITLE
Authentication Question before switching

### ISSUE THREAD

**Issue by odesey** [VeliovGroup/flow-router#15]
I am working on a project and it was started using `Flow-Router`. I needed route authentication and implemented it following this post:

https://medium.com/@satyavh/using-flow-router-for-authentication-ba7bb2644f42

Now that `Flow-Router` is no longer supported, I would like to switch to using your package. 

My question is, will route authentication be handled different in your package compared to the original `Flow-Router`

Thanks.

**Comment by dr-dimitru** [comment]
Hello @odesey ,

This logic remains untouched. Actually default FR remained the same, I'm just fixing the bugs.
Hope this will help to make a decision.

**Comment by odesey** [comment]
Thanks for your response.

Can I use the `waitOn` hook to achieve the same result as what is being done now? (based on the blog post)

**Comment by dr-dimitru** [comment]
Yes, you can, but it will be over complex, you may do it using `Tracker` in `waitOn`.
No need to use `waitOn` for this, I suggesting to not change approach suggested in the article you referring to.

**Comment by odesey** [comment]
Thanks!

**Comment by dr-dimitru** [comment]
Let me know about your experience, after you will try.
