### ISSUE TITLE
Nested groups triggersEnter are not fired

### ISSUE THREAD

**Issue by kpala** [VeliovGroup/flow-router#16]
It seems nested groups do not fire all triggersEnter functions. I'm using version 3.1.3.

Consider the following example:

```javascript
const loginGroup = FlowRouter.group({
    triggersEnter: [() => {
        console.log('login group');
    }]
});

const rootGroup = loginGroup.group({
    triggersEnter: [() => {
        console.log('root group');
    }]
});

rootGroup.route('/', {
    action() {
        ...
    },
    triggersEnter: [() => {
        console.log('root route');
    }]
});
```

The output in console is then:

```
root group
root route
```

while with `kadira:flow-router@2.12.1` it is (as it should be):

```
login group
root group
root route
```

**Comment by dr-dimitru** [comment]
Hello @kpala ,

Sorry for late response.
Thank you a lot for submitting this issue.

This should be fixed in [v.3.2.0](https://github.com/VeliovGroup/flow-router/releases/tag/3.2.0), please upgrade and let me know if it work for you.
