### ISSUE TITLE
Making documentation in pages/wiki?

### ISSUE THREAD

**Issue by vbgm** [VeliovGroup/flow-router#17]
The flow-router-extra's doc seem to get too large to reside on one readme page, any thoughts on moving it to wiki? And maybe eventually unite with the original flow-router?

**Comment by dr-dimitru** [comment]
Hello @vblagomir ,

> doc seem to get too large to reside on one readme page

Agree on that.

> any thoughts on moving it to wiki

Good idea, I'll schedule this for next release. If you wish to send a PR for wiki, take a look on [how we manage wiki docs](https://github.com/VeliovGroup/Meteor-Files/tree/master/docs) in Meteor-Files package, which is good example.

Now we're working on big stability release (*as you can see from recent commits*).

>  And maybe eventually unite with the original flow-router?

I wish so, but Arunoda has [different point of view](https://forums.meteor.com/t/what-a-best-alternative-for-flowrouter-now-after-lost-arunoda-and-kadira/31846/56?u=dr.dimitru)

**Comment by dr-dimitru** [comment]
@vblagomir looks like it's done, wdyt?

**Comment by vbgm** [comment]
Superb! :-)

**Comment by dr-dimitru** [comment]
@vblagomir thank you for this idea.

Please, support this project by:
 - Star on [GitHub](https://github.com/VeliovGroup/flow-router)
 - Star on [Atmosphere](https://atmospherejs.com/ostrio/flow-router-extra)
 - Check [other packages](https://github.com/search?o=desc&q=topic%3Ameteor-package+org%3AVeliovGroup&s=stars&type=Repositories) we have made
