### ISSUE TITLE
bug with dynamic import

### ISSUE THREAD

**Issue by nacimgoura** [VeliovGroup/flow-router#18]
Hello,
I would like to call a page by a dynamic import depending on the parameter of the url, but it doesn't work.
If I do not import with a parameter it works correctly.
This is my code : 
![screenshot from 2017-07-28 14-01-17](https://user-images.githubusercontent.com/9990521/28718444-eedc3cd0-739d-11e7-8286-df16dbf0176d.png)
This is the error : 
![screenshot from 2017-07-28 14-05-05](https://user-images.githubusercontent.com/9990521/28718452-f7f48c3c-739d-11e7-8c27-e044df2db947.png)

I do not know how to solve it.
Thank you for your help!

**Comment by dr-dimitru** [comment]
Hello @nacimgoura ,

It's not a bug, it's Meteor's feature.

In short - you can not use variables it import/require path, only solid __String__ is supported.

See:
 1. [This forum thread](https://forums.meteor.com/t/how-to-use-import-require-with-dynamic-path/21955)
 2. [One more forum thread](https://forums.meteor.com/t/dynamic-imports-file-names/32018/2)

Let me know if it helped you.

**Comment by nacimgoura** [comment]
Sorry for creating this issue, i didn't know.

Thank you!

**Comment by dr-dimitru** [comment]
@nacimgoura no worries, I stepped in the same issue after `meteor@1.5` with dynamic imports was released :)

**Comment by dr-dimitru** [comment]
Please, support this project by:
 - Star on [GitHub](https://github.com/VeliovGroup/flow-router)
 - Star on [Atmosphere](https://atmospherejs.com/ostrio/flow-router-extra)
 - Check [other packages](https://github.com/search?o=desc&q=topic%3Ameteor-package+org%3AVeliovGroup&s=stars&type=Repositories) we have made

**Comment by nacimgoura** [comment]
Also, It is possible to use waitOn in FlowRouter.group ?

**Comment by dr-dimitru** [comment]
> Also, It is possible to use waitOn in FlowRouter.group ?

Yes, since [`v3.2.0`](https://github.com/VeliovGroup/flow-router/releases/tag/3.2.0), see #11
