### ISSUE TITLE
Support for body-class

### ISSUE THREAD

**Issue by talha-asad** [VeliovGroup/flow-router#2]
`lookback:body-class` doesn't seem to work.

**Comment by dr-dimitru** [comment]
Do you get any errors in console?

**Comment by dr-dimitru** [comment]
I've checked the `lookback:body-class` source code, it's known issue, and it's easy to solve, from the docs:

> Note: if you're using any package which requires original FR namespace, throws an error, you can solve it with next code:
> 
> ``` js
> // in /lib/ directory
> Package['kadira:flow-router'] = Package['ostrio:flow-router-extra'];
> ```

**Comment by talha-asad** [comment]
Should this be used inside `Meteor.startup` ? I wonder why doesn't this package does this internally already as it seems to be a drop in replacement for the original flow-router.

Also i don't understand if i should remove the original package or should i add this one along with it? This should be more clearly defined in the Readme.

**Comment by dr-dimitru** [comment]
> Should this be used inside Meteor.startup ?

Nope, just in `/lib/` directory of your project

> why doesn't this package does this internally 

Not currently possible, if I'll add this into package you will need to place it at the very top of `.meteor/packages` file

> should remove the original package or should i add this one along with it

You should use **only one** package, otherwise they will have conflicts

**Comment by talha-asad** [comment]
What about all the packages that imply `flow-router`, it'll get loaded anyway, no?

I'll try the package override.

**Comment by dr-dimitru** [comment]
> What about all the packages that imply `flow-router`

Could you list such packages?

**Comment by dr-dimitru** [comment]
@talha-asad ?

**Comment by dr-dimitru** [comment]
Closed due to silence
