### ISSUE TITLE
Compatibility issue with useraccounts:flow-routing

### ISSUE THREAD

**Issue by Almaju** [VeliovGroup/flow-router#21]
Hi and thanks for the nice work!

I ran into some weird issues (for instance template helpers not working) after switching to your package. After hours of investigations and lot of tests, I identified the issue coming from useraccounts:flow-routing.

You can find a reproduction of the bug here: https://github.com/Almaju/fre-testing
The page shall display "/" instead of "home". This bug disappears as soon as I remove the useraccounts:flow-routing package (import has to be uncommented on /lib/router.js though).

I will investigate a bit more on this and why it happens.

**Comment by dr-dimitru** [comment]
Hello @Almaju ,

Unfortunately `useraccounts:flow-routing` package is not compatible with this package.
I recommend to fork it and replace `kadira:flow-router` with `ostrio:flow-router-extra`. Full switch to `ostrio:flow-router-extra` may require some work.

Or at least [leave an issue](https://github.com/meteor-useraccounts/flow-routing/issues) and ask for support of `ostrio:flow-router-extra`.

**Comment by Almaju** [comment]
Thanks for the answer! I posted an issue on their repo. Might be useful to inform this compatibility issue in the doc though. :)

**Comment by dr-dimitru** [comment]
Honestly `useraccounts:flow-routing` looks stale and dead, lots of open issues for a long time, and codebase remains untouched since 2015.

Hope we're or someone quicker will fork `useraccounts:flow-routing` and adapt it for `ostrio:flow-router-extra`.

**Comment by kwuite** [comment]
Pushed a package to atmoshpere with flow-routing-extra support.

https://atmospherejs.com/mealsunite/flow-routing-extra

**Comment by dr-dimitru** [comment]
@kwuite awesome 😃 
Don't you mind if we will add your package to our Readme? If so, - drop me single line description.

**Comment by kwuite** [comment]
@dr-dimitru , sure thing, just keep the description equal to the original package I'd say. We will keep the package up-to-date for our needs and if there are errors just push them to us;).

**Comment by dr-dimitru** [comment]
Done, thank you @kwuite .
