### ISSUE TITLE
render into specific "regions"

### ISSUE THREAD

**Issue by jamgold** [VeliovGroup/flow-router#22]
I believe the original flow-router supported rendering content into specific regions. How is `this.render` of ostrio handling this? Does `{{>yield}}` take an argument?

**Comment by dr-dimitru** [comment]
Hello @jamgold ,

## TL;TR;
`{{>yield}}` and built-in `.render()` is highly optimized for smooth rendering and saving user's UI from FPS drop, which is perfect for projects with a lot of animations.

`{{>yield}}` can be used only once per "layout" template.

[Here similar question](https://github.com/VeliovGroup/flow-router/issues/12#issuecomment-306286006) where I've comprehensively explained how to use regions in FR-Extra, and why it's slightly different.

**Comment by jamgold** [comment]
Thanks so much for the quick response

**Comment by dr-dimitru** [comment]
@jamgold sure, np.
Hope it was helpful.

Please, support this project by:
 - Star on [GitHub](https://github.com/VeliovGroup/flow-router)
 - Star on [Atmosphere](https://atmospherejs.com/ostrio/flow-router-extra)
 - Check [other packages](https://github.com/search?o=desc&q=topic%3Ameteor-package+org%3AVeliovGroup&s=stars&type=Repositories) we have made
