### ISSUE TITLE
Server side Routes

### ISSUE THREAD

**Issue by jamgold** [VeliovGroup/flow-router#23]
I am writing an application that should provide some REST interface, but can't get server side routes working, not even with Picker. Am I missing something?

**Comment by dr-dimitru** [comment]
Hello @jamgold ,

For this purpose you need to create local package (*placed above `ostrio:flow-router-extra` in the `.meteor/packages` file*).

It can be easily done using [`webapp` package](https://docs.meteor.com/packages/webapp.html) only, or extending it with solutions like `express.js`, `connect.js` and similar.

Maybe simpler will be to use [`simple:rest` package](https://atmospherejs.com/simple/rest).

It's up to you, saying that `ostrio:flow-router-extra` should be considered as Client-only solution

**Comment by jamgold** [comment]
Hello @dr-dimitru ,

thank you for answering. I have figured out how to use Picker. My main confusion was that I have assets in public for which there are not routes, of course. If a request is made to something in public that does not exist, the not-found route kicks in, which unfortunately is indistinguishable from a successful request (no status 404). Do you know how to manipulate the HTTP Status with this router?

**Comment by dr-dimitru** [comment]
Not currently possible with Meteor. It's Meteor's "feature" and not related to FR package. It's common for most of the front-end JS solutions, and not Meteor specific.

But if you're looking `404` response codes (*genuine status code*) for SEO (Google, Yahoo, etc.) optimization, take a look on:
 - [Enhanced `spiderable` package](https://github.com/VeliovGroup/jazeee-meteor-spiderable#enable-default-404-response-if-youre-using-flow-router)
 - [Prerendering](https://ostr.io/info/prerendering#genuine-status-code)

**Comment by jamgold** [comment]
Thank you again, will check it out.

**Comment by adamgins** [comment]
@dr-dimitru thanks for this package... just checking if I need to serve a server side router with `webapp`  https://docs.meteor.com/packages/webapp.html to a route like `https://localhost:3000/someroutepart1/someroutepart2` Flow router is sending back a "not found" 

So, I need to get in before FlowRouter and the only way to do that is add me `webapp` code in a package before FlowRouter gets loaded? https://github.com/VeliovGroup/flow-router/issues/23#issuecomment-331670213

it seems like if I hit `https://localhost:3000/someroutepart1` webapp gets it.. .but as soon as I add some stuff ike `someroutepart2` then it seems to grab it

BTW, I did post here https://forums.meteor.com/t/flowrouter-is-grabbing-my-requests-from-webapp/49888 as I know this is not a bug
