### ISSUE TITLE
Switch fast-render from abandoned meteorhacks to maintained staringatlights dist

### ISSUE THREAD

**Issue by nadeemja** [VeliovGroup/flow-router#24]
Hi,

The meteorhacks:fast-render package is abandoned and breaks in newer meteor versions. 

Could you update your deps to staringatlights:fast-render?

Thanks :)

**Comment by nadeemja** [comment]
See https://github.com/meteor/meteor/issues/9003

**Comment by dr-dimitru** [comment]
Hello @nadeemja ,

Do you mean [in the tests](https://github.com/VeliovGroup/flow-router/blob/master/package.js#L29)?

**Comment by nadeemja** [comment]
Oh. My mistake. We were getting error related to the meteorhacks version, and couldn't see anywhere else it might've been included. Weird :(

**Comment by dr-dimitru** [comment]
I'll keep it open. I think you're right, and newer version should be used in tests.
