### ISSUE TITLE
Dash in paths not recognized as separators

### ISSUE THREAD

**Issue by nicooprat** [VeliovGroup/flow-router#25]
I had this kind of routes working with original FlowRouter: `/@:username/:storyId-:storySlug?`.

Now, the second part is considered to be a unique block `:storyId-:storySlug?` according to this regex:

https://github.com/VeliovGroup/flow-router/blob/110a27945417f9fbc45a6262d7245a9335d1c704/client/router.js#L8

Removing the `\-` makes it work again: https://regex101.com/r/CadP4l/2.

Is it something done on purpose? Is there any other recommended way of defining routes?

Thanks.

**Comment by dr-dimitru** [comment]
Hello @nicooprat ,

> Is it something done on purpose?

Yes. Take a look on [this commit](https://github.com/VeliovGroup/flow-router/commit/34074d2a63d4a7c783f90257ab94a53758f0190c#diff-3dd91952b25589a53f18280a382b9567) and [this PR](https://github.com/kadirahq/flow-router/pull/654).

As this was done almost a year ago, not sure if it's safe to roll back.

> Is there any other recommended way of defining routes?
Yes, split each param using forward slash `/`

WDYT?

**Comment by nicooprat** [comment]
I understand. Pretty hard for me too to change all my URIs :D And I think it's more meaningful in my case to configure path like this ; would be weird to have `id/slug`...

Would it be possible to make this regex configurable? Or better, an array of "URI delimiters"?

By the way, are optional params still a thing? In this case: `/@:username/:storyId/:storySlug?/:chapterId/:chapterSlug?`, what would happen if `storySlug` is missing?

**Comment by dr-dimitru** [comment]
> Pretty hard for me too to change all my URIs :D And I think it's more meaningful in my case to configure path like this ; would be weird to have id/slug...

We're okay to use slug after slash, for example:
 - https://veliovgroup.com/article/yMCeuYPdubaeWeYDP/active-citizen
 - https://veliovgroup.com/article/yMCeuYPdubaeWeYDP

> Would it be possible to make this regex configurable? Or better, an array of "URI delimiters"?

This is a good idea, marked this thread as [enhancement]. PR is welcome, or we will add this feature at the next release.

> By the way, are optional params still a thing?

Yes

> /@:username/:storyId/:storySlug?/:chapterId/:chapterSlug? what would happen if storySlug is missing?

`storySlug` can not be omitted as `chapterId` is required and should optional too for this case.

**Comment by nicooprat** [comment]
Made the simplest change I could think of: https://github.com/VeliovGroup/flow-router/pull/26

I think it would be better to create a setter function taking an array of strings as parameters... But I'm really not good enough in Regex :)

**Comment by nicooprat** [comment]
Thanks! Do you plan to bump the package version & publish on Atmosphere soon?

**Comment by dr-dimitru** [comment]
@nicooprat yes, working on it now. Too many packages are connected. Decided to have a sleep before sending it to Package Manager :)

**Comment by nicooprat** [comment]
👍 thanks!

**Comment by dr-dimitru** [comment]
@nicooprat does it work for you?

**Comment by nicooprat** [comment]
Yes, the override is working. Didn't see any bug. Thanks again!
