### ISSUE TITLE
whileWaiting() throws No such Layout

### ISSUE THREAD

**Issue by shizznet** [VeliovGroup/flow-router#29]
@dr-dimitru 
I have followed the document and my whileWaiting function looks like this

`whileWaiting() {
    this.render('mainLayout', 'Spinner');
}`

Where `mainLayout` is my main template with yield ,
and `Spinner` is my loading template.

![image](https://user-images.githubusercontent.com/8719925/31483022-66cab2cc-af48-11e7-84b4-93709cfe1aa2.png)

Please help me with this, if I remove whileWaiting function the code works perfectly

<hr>
Update: This is issue happens only at the landing page, if I use whileWaiting on other page also if the user navigates to the page whileWaiting works, now if the user refreshes the page it will give me the same error as mentioned above.

Note: this only works when users navigates through clicks not when user directly visits the page or refreshes the page.

**Comment by shizznet** [comment]
So here it goes .... After long hours of scratching my head and googling for solution, I found a solution myself.

I needed to require layouts with template name "`mainLayout`" and "`Spinner`" to make it work. I don't know why but it's not mentioned in the document.

**Comment by dr-dimitru** [comment]
Hello @shizznet ,

Sorry for late response, *somehow missed this ticket*.

Could you please show how do you require those templates, so I will update the docs?

**Comment by shizznet** [comment]
```
client/
common/
imports/
--config/
----ui/
------components/   #All UI and Respective js components  come here
------routes/
--------MainRoutes.js  #My router file
------styles/
lib/
private/
public/
server/
```
My MainRoutes.js looks like this

```
import { FlowRouter } from 'meteor/ostrio:flow-router-extra'
import { Session } from 'meteor/session'
import UIkit from 'uikit'
import Icons from 'uikit/dist/js/uikit-icons'
UIkit.use(Icons);
require('../components/layout/main.html'); //This is how I solved the problem
require('../components/base/Spinner.html'); //This is how I solved the problem

FlowRouter.route('/', {
	title: 'Title',
	meta: {
		url: {
			property: 'og:url',
			itemprop: 'url',
			content() {
				return document.location.href;
			}
		},
		keywords: {
			name: 'keywords',
			itemprop: 'keywords',
			content(params, query, data) {
				if (data == null) {
					data = {};
				}
				return data.keywords;
			}
		},
		description: {
			name: 'description',
			itemprop: 'description',
			property: 'og:description',
			content(params, query, data) {
				if (data == null) {
					data = {};
				}
				return data.description;
			}
		}
	},
	link: {
		canonical() {
			return document.location.href;
		}
	},
	action() {
		Session.set('utm', BASE_CATEGORY);
		this.render('mainLayout', 'Home')
	},
	whileWaiting() {
		this.render('mainLayout', 'Spinner');
	},
	waitOn() {
		return [
			import ('../components/Home/HomeComponent.js'),
			Meteor.subscribe('getContent', BASE_CATEGORY, BASE_CATEGORY)
		]
	},
	waitOnResources() {
		var data = Content.find({name: BASE_CATEGORY}).fetch()
		return {
			images: [
				BASE_SOURCE + data[0].image_web,
				BASE_SOURCE + data[0].image_mobile
			]
		};
	}
})
```

Hope this helps you @dr-dimitru 

Thank you for the library :)
