### ISSUE TITLE
Could you participate the "What a best alternative for FlowRouter now after lost arunoda and kadira?"

### ISSUE THREAD

**Issue by thearabbit** [VeliovGroup/flow-router#3]
[What a best alternative for FlowRouter now after lost arunoda and kadira?](https://forums.meteor.com/t/what-a-best-alternative-for-flowrouter-now-after-lost-arunoda-and-kadira/31846)

**Comment by dr-dimitru** [comment]
Hi @thearabbit ,

Thank you for pointing me to this thread.
I've left my thoughts about merge. And already got some response.

I'll keep this fork up to date. Wish @arunoda will reply to any of currently active threads.

**Comment by thearabbit** [comment]
Thanks for your keep this.
But the next project, I will try `React, React-Route...`.
I don't mind to use `Blaze`.
