### ISSUE TITLE
Uncouple Blaze

### ISSUE THREAD

**Issue by dr-dimitru** [VeliovGroup/flow-router#33]
Uncouple Blaze by moving `BlazeRenderer` into separate package.

See [this thread](https://github.com/meteor/meteor/issues/9419#issuecomment-347210205)

**Comment by derwaldgeist** [comment]
Thanks for opening this! I think this is a major step forward to FlowRouter extra's general acceptance. One question related to this: Is it possible to use FlowRouter extra (as it is now) in combination with the old "BlazeLayout" package? I saw that FlowRouter extra has its own render() method, but this would mean refactoring all existing (old-FlowRouter) routes.

**Comment by derwaldgeist** [comment]
Just found this: https://github.com/VeliovGroup/flow-router/issues/32#issuecomment-343578907 which answers my question.

**Comment by dr-dimitru** [comment]
Yes, it will work, and we even test it for every release.
Built-in `. render()` has it's own features for heavily animated websites, where FPS matters.

**Comment by dr-dimitru** [comment]
@derwaldgeist @krishaamer this request is implemented, and published as [`v3.4.4`](https://github.com/VeliovGroup/flow-router/releases/tag/3.4.4).

Feel free to contribute into [React usage docs](https://github.com/VeliovGroup/flow-router/issues/40).

Please confirm `v3.4.4` works smoothly on your end.

**Comment by eleventy** [comment]
Just updated tot `3.4.5`, everything is running smoothly ( React only app ), and finally my last dependency on `jquery` disappeared. All the following packages are gone:
```
blaze                     removed from your project
bundle-visualizer         removed from your project
jquery                    removed from your project
observe-sequence          removed from your project
ostrio:flow-router-extra  upgraded from 3.4.3 to 3.4.5
spacebars                 removed from your project
templating                removed from your project
templating-compiler       removed from your project
templating-runtime        removed from your project
```

Nice work!

**Comment by dr-dimitru** [comment]
@eleventy awesome, thank you for feedback!
