### ISSUE TITLE
Boilerplate templating example throwing "Cannot Find Module" exceptions

### ISSUE THREAD

**Issue by davidrea** [VeliovGroup/flow-router#37]
I tried incorporating FlowRouter Extra into a simplistic SPA I'm working on and got "Cannot Find Module" exceptions for any .js or .html files I attempted to import in the /lib/routes.js file. To verify the issue wasn't introduced elsewhere in my app, I created a new empty Meteor app and populated only the files listed in the [Templating guid](https://github.com/VeliovGroup/flow-router/blob/master/docs/templating.md), with contents exactly as-documented.

Even there, on running `meteor`, I get these errors in the console and a "Your app is crashing" message:

Error: Cannot find module '/imports/client/layout/layout.js'
Error: Cannot find module '/imports/client/loading/loading.html'

I made sure babel-runtime is included in the project and installed; I'm at a loss for how to troubleshoot this further, as the files it's complaining about are definitely present in the filesystem at the paths specified.

Any guidance will be much appreciated; I don't have any hair left to pull out! ;-)

**Comment by davidrea** [comment]
I went through a did a more careful cleanroom test-out of the package, following the structure and import chain recommended in the Meteor Guide, and wasn't able to reproduce this error... Closing now, though I did find a mistake in the boilerplate (unrelated) for which I'll open a new issue.

**Comment by mikhail-shishov** [comment]
Hello @davidrea ,

Thanks for reporting on this issue! We're glad that you've solved it on your own.

Please, support this project by:
 - Star on [GitHub](https://github.com/VeliovGroup/Meteor-Files)
 - Star on [Atmosphere](https://atmospherejs.com/ostrio/files)
 - Check [other packages](https://github.com/search?o=desc&q=topic%3Ameteor-package+org%3AVeliovGroup&s=stars&type=Repositories) we have made
 - Share on [Facebook](https://www.facebook.com/sharer.php?u=https%3A%2F%2Fgithub.com%2FVeliovGroup%2FMeteor-Files) and [Twitter](https://twitter.com/share?url=https%3A%2F%2Fgithub.com%2FVeliovGroup%2FMeteor-Files)
 - [Donate via PayPal](https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=FVDSXRFW9VGA2)
