### ISSUE TITLE
Setup Issues - this.render()

### ISSUE THREAD

**Issue by cdoe** [VeliovGroup/flow-router#45]
Hello,

I'm working on setting up flow-router for a new project and having real trouble getting `this.render()` to do anything.  No matter what I try, I continue to see `Error: '.render()' - Requires 'blaze' and 'templating', or 'blaze-html-templates' packages to be installed` and can't get anything to show up on screen.

To try and troubleshoot most clearly, a recent one of my experiments went like:
`meteor create test --full`
`cd test`
`meteor remove kadira:flow-router`
`meteor add ostrio:flow-router-extra`
Then in _imports > startup > clients > routes.js_, I adjusted the import statement and changed `BlazeLayout.render()` to `this.render()`

Meteor _--full_ mode starts with _blaze-html-templates_ included, so I expected everything to work, but I can't get rid of this error or get anything to render.  I've tried adding/removing every combination of those 3 packages imaginable.

Thanks in advance for any insight into what will likely turn out to be a very trivial problem ;)

**Comment by dr-dimitru** [comment]
Hello @cdoe ,

Make sure 
```
blaze
templating
blaze-html-templates
```
Are placed above `ostrio:flow-router-extra` in `.meteor/packages` file, see https://github.com/VeliovGroup/flow-router/issues/43 for more info. PR https://github.com/VeliovGroup/flow-router/pull/44 will solve this issue

**Comment by dr-dimitru** [comment]
@cdoe please update to the latest release, this issue should be solved now - [`v3.4.6`](https://github.com/VeliovGroup/flow-router/releases/tag/3.4.6)

**Comment by dr-dimitru** [comment]
@cdoe please update this thread with your results. Is the latest update solved your issue?

**Comment by cdoe** [comment]
The update seemed to fix all my problems.
Kudos for the super quick reply, @dr-dimitru! Super helpful!

From what I can tell, it doesn't matter how those packages are arranged.
I currently have just `blaze-html-templates` and `ostrio:flow-router-extra` installed.  Changing their order in `.meteor/packages` doesn't break anything.  And in this case, it doesn't seem necessary to install `blaze` or `templating`, right?

Thanks again!

**Comment by dr-dimitru** [comment]
[My suggestion](https://github.com/VeliovGroup/flow-router/issues/45#issuecomment-364086781) was related to `v3.4.5` (*previous release*). Since I've released an update (`v3.4.6`), order of packages at `.meteor/packages` file no longer matter.

But you're still required `blaze-html-templates` __or__ `blaze` __and__ `templating`, e.g.:
```js
'blaze-html-templates' || ('blaze' && 'templating');
```

Let me know if this info was helpful.

**Comment by cdoe** [comment]
Yes.  Very helpful.  It is a bit more clear stated that way.
Thanks again!

**Comment by dr-dimitru** [comment]
Please, support this project by:
 - Star on [GitHub](https://github.com/VeliovGroup/flow-router)
 - Star on [Atmosphere](https://atmospherejs.com/ostrio/flow-router-extra)
 - Check [other packages](https://github.com/search?o=desc&q=topic%3Ameteor-package+org%3AVeliovGroup&s=stars&type=Repositories) we have made
