### ISSUE TITLE
unsubscribe only after next page is rendered

### ISSUE THREAD

**Issue by achtan** [VeliovGroup/flow-router#46]
when i click on (PageA) link to navigate to next page (PageB), it seems like the "unsubscribe" on PageA is fired before the app content is "re-rendered".

So i can see a few ms "blink" when the PageA with no-data and just after that is PageB rendered.

**Comment by dr-dimitru** [comment]
Hello @achtan ,

This is expected behavior, as you don't want to have PageB have multiple subs for both PageA and PageB. To mitigate this you can use `whileWaiting` hook.

There is no silver bullet to solve this. On our end we're checking if data is populated on template level to display "Loading..." state if a Template has no data.

**Comment by achtan** [comment]
thx for clarification

**Comment by dr-dimitru** [comment]
Please, support this project by:
 - Star on [GitHub](https://github.com/VeliovGroup/flow-router)
 - Star on [Atmosphere](https://atmospherejs.com/ostrio/flow-router-extra)
 - Check [other packages](https://github.com/search?o=desc&q=topic%3Ameteor-package+org%3AVeliovGroup&s=stars&type=Repositories) we have made

**Comment by achtan** [comment]
one more question: why is unsubscribing and subscribing happening in this setup:
````js
const group = FlowRouter.group({
  prefix: '/members',
  whileWaiting() {
    this.render('Layout', 'Loading');
  },
  waitOn: function(params, queryParams) {
      return [
        Meteor.subscribe('AdminSubscription'),
      ];
  },
});


group.route('/', {
  action() {
    this.render('Layout', 'Members');
  }
});

group.route('/:userId', {
  action() {
    this.render('Layout', 'Member');
  }
});
````
as you can see i have only one subscription in the group definition... so there is no need to do re-subscribe when i move from `/members` to `/members/:userId`

**Comment by dr-dimitru** [comment]
@achtan good question. Due to non-reactivity of parameters (arguments) passed into the hooks, we have to re-run it to make sure it called with right and updated arguments.

**Comment by achtan** [comment]
ok, and is there a way to subscribe only-once ... or any solution to my problem.. ? thx

**Comment by dr-dimitru** [comment]
@achtan template level subscriptions. Which can be done on the `Layout` template level. I see two options:
 1. Create separate `Layout` template for this group of routes with template level subscription;
 2. Create conditional `Layout` template level subscription.

Example:
```js
import { Template } from 'meteor/templating';

Template.Layout.onCreated(function () {
  this.subscribe('myAwesomePub');
});
```

One disadvantage - __It wouldn't wait for subs t be ready__.

One more option is the caching mechanism, like `meteorhacks:subs-manager`.
We're using `meteorhacks:subs-manager` for a long time, it does what it needs.
