### ISSUE TITLE
Fast-render doesn't work

### ISSUE THREAD

**Issue by dhamaniasad** [VeliovGroup/flow-router#47]
### I have a suggestion:
It seems like fast-rendering does not work with `flow-router extra`. The `staringatlights:flow-router` package has some code around this that makes the fast rendering work with `staringatlights:fast-render`.
Here's a link to the code: https://github.com/abecks/flow-router/blob/master/server/plugins/fast_render.js

**Comment by janat08** [comment]
Basically just copy and pasting the file hasn't worked.

**Comment by dr-dimitru** [comment]
Hello @dhamaniasad @janat08 ,

Does it work if you use [8-40 lines](https://github.com/abecks/flow-router/blob/master/server/plugins/fast_render.js#L8-L40)?

**Comment by janat08** [comment]
I forgot to import flow-router instance into fast_render.js (and some other stuff), it works with all of the lines. When will you publish?

**Comment by dhamaniasad** [comment]
@dr-dimitru I copy pasted the entire file into my `/lib` folder, but the first few lines are just checking if the package is installed, the code should function without it just fine.

**Comment by dr-dimitru** [comment]
Thank you guys @dhamaniasad @janat08 ,

Published as [`v3.5.0`](https://github.com/VeliovGroup/flow-router/releases/tag/3.5.0).
Let me know how it works for you.

**Comment by dr-dimitru** [comment]
Feel free to reopen it in case if the issue is still persists on your end.
