### ISSUE TITLE
There is no route for the path: /

### ISSUE THREAD

**Issue by odesey** [VeliovGroup/flow-router#5]
I am testing you package and switched out to default `kadira:flow-router` package for yours. Everything else stayed the same and I am getting the following error in the console:
`There is no route for the path: /`

here is how I have the routes file configured:
```javascript
import { FlowRouter } from 'meteor/ostrio:flow-router-extra';
import { BlazeLayout } from 'meteor/kadira:blaze-layout';

const allRoutes = FlowRouter.group({
  prefix: '',
  name: 'defaultRoutes',
  triggersEnter: [function () {
    Meteor.defer(function () {
      $('body').addClass('theme-cyan');
    });      
  }],
});

BlazeLayout.setRoot('body');
// Set up all routes in the app
allRoutes.route('/', {
  name: 'App.home',
  action() {
    BlazeLayout.render('App_body', { main: 'App_home', top: 'navbar', toolbar: 'toolbar', side: 'sidemenu' });
  },
});


```

Switching back to the kadira package resolves the error.

Am I missing something?

Thanks.

**Comment by dr-dimitru** [comment]
Hello @odesey ,

 1. Your code looks good, should work. Is there any error stack trace? Usually this error doesn't comes alone.
 2. What if you define `/` route out of the group? As test-case only

**Comment by odesey** [comment]
So, I did some more testing. This may be related to the `philippspo:momentum-flow-router` package. I am using that package for page transitions and I think there may be an issue with your package the the one I just mentioned.

In addition to throwing the error, the page transitions no longer work once I switch to your package instead of the basic `flow-router` package

**Comment by dr-dimitru** [comment]
@odesey well, is there any errors and its stack trace? Except `There is no route for the path: /` that will be a good start to fix it.

**Comment by dr-dimitru** [comment]
I believe it's caused by interference by [package dependency](https://github.com/PhilippSpo/momentum-flow-router/blob/master/package.js#L15) on original flow-router, if that will be `weak` it may help a lot.

You can fork `philippspo:momentum-flow-router` and place to `/packages` directory under your project, update its dependencies to the latest versions and replace `kadira:flow-router` dependency with `ostrio:flow-router-extra`

And this line may also help to your issue:
```js
Package['kadira:flow-router'] = Package['ostrio:flow-router-extra'];
```

**Comment by odesey** [comment]
Thanks for the suggestion.

I will test it out and provide feedback.

**Comment by odesey** [comment]
Did as you suggested and everything works now, including the transitions.

Thanks for the help and great package!

**Comment by dr-dimitru** [comment]
@odesey I'm glad it helped you. Thank you for choice of this package.

Please, support this project by:
 - Star on [GitHub](https://github.com/VeliovGroup/flow-router)
 - Star on [Atmosphere](https://atmospherejs.com/ostrio/flow-router-extra)

**Comment by nacimgoura** [comment]
I have the same issue (There is no route for the path: /)

```

import { FlowRouter } from 'meteor/ostrio:flow-router-extra';
import { FlowRouterTitle } from 'meteor/ostrio:flow-router-title';

// Import layout
import '/imports/ui/layouts/body/body';
import '/imports/ui/layouts/header/header';
import '/imports/ui/layouts/sidebar/sidebar';

// import pages
import '/imports/ui/pages/home/home';
import '/imports/ui/pages/account/account';
import '/imports/ui/pages/not-found/not-found';


// Set up all routes in the app
FlowRouter.route('/', {
    name: 'home',
    title: 'Recherche',
    action(params, queryParams, data) {
        this.render('bodyLayoutTpl', 'homeTpl');
    },
});

new FlowRouterTitle(FlowRouter);
```

The page displays correctly but I have this error in the console :disappointed:

**Comment by dr-dimitru** [comment]
Hello @nacimgoura ,
Have you removed original FlowRouter?

**Comment by nacimgoura** [comment]
No it is still present. Should we remove it?

**Comment by dr-dimitru** [comment]
@nacimgoura yes, remove it please.

**Comment by nacimgoura** [comment]
Yes, removing original flowRouter, I no longer have the error. Unless I am mistaken, it's not specified in the documentation.
Thank your for your help!

**Comment by dr-dimitru** [comment]
> it's not specified in the documentation.

Good catch, it was there, now it's lost, going to add it back.
Thank you a lot

**Comment by rashmimhatre100** [comment]
Hello I am facing same issue, getting error =>There is no route for the path: /
And no other error is there in console. Also removed kadira flowrouter but error still persist.

**Below are packages I am using:**
twbs:bootstrap
fortawesome:fontawesome
kadira:blaze-layout
iassureit:user-management
babrahams:editable-text-wysiwyg-bootstrap-3
babrahams:editable-text
pfafman:photo-up
themeteorchef:bert
harrison:papa-parse
alanning:roles
email@1.2.3
dynamic-import@0.1.1
session@1.1.7
benjaminrh:user-session
accounts-password@1.4.0
accounts-base@1.3.2
momentjs:moment
themeteorchef:jquery-validation
bundle-visualizer
ostrio:flow-router-extra
 
**Router file:**
```js
import { FlowRouter } from 'meteor/ostrio:flow-router-extra';
FlowRouter.route('/', {
  name: 'homepage',
  action() {
    this.render('homepage', 'login');
  }
});
```
Please help me out with this. Thanks in advance!

**Comment by dr-dimitru** [comment]
@rashmimhatre100 

Looks like route registered too late.
How do you import a file with routes?

**Comment by rashmimhatre100** [comment]
I am really sorry my bad I was using custom package and kadira flowrouter was there. I removed it and error is gone now. Thank you so much.

**Comment by dr-dimitru** [comment]
@rashmimhatre100 no worries, I'm glad it's solved now.

Please, support this project by:
 - Star on [GitHub](https://github.com/VeliovGroup/flow-router)
 - Star on [Atmosphere](https://atmospherejs.com/ostrio/flow-router-extra)
 - Check [other packages](https://github.com/search?o=desc&q=topic%3Ameteor-package+org%3AVeliovGroup&s=stars&type=Repositories) we have made
