### ISSUE TITLE
How can I use this with kadira:blaze-layout, if BlazeLayout requires kadira:flow-router?

### ISSUE THREAD

**Issue by jaredtmartin** [VeliovGroup/flow-router#57]
I want to use this package instead of kadira:flow-router and I see in the docs that this package is compatible with BlazeLayout, but kadira:blaze-layout depends on kadira:flow-router and having that installed causes conflicts.  So what should I do?

**Comment by coagmano** [comment]
`kadira:blaze-layout` does not rely on `kadira:flow-router`:
https://github.com/kadirahq/blaze-layout/blob/master/package.js

**Comment by dr-dimitru** [comment]
@coagmano thank you for quick follow-up
@jaredtmartin as mentioned by @coagmano `kadira:blaze-layout` doesn't have dependencies.

try to:
```shell
meteor remove kadira:flow-router kadira:blaze-layout
meteor add kadira:blaze-layout
```

**Comment by dr-dimitru** [comment]
@jaredtmartin have you solved this one?

**Comment by dr-dimitru** [comment]
Closed due to silence at issue owner end.
Feel free to reopen it in case if the issue still persists on your end.
