### ISSUE TITLE
Feature proposal: Render Locally Scoped Templates

### ISSUE THREAD

**Issue by vbgm** [VeliovGroup/flow-router#6]
I have started to use [https://github.com/nathantreid/blaze-modules](url) and thought that flow-router-extra could support scoped templates in it's this.render() method.

Namely, I suggest to allow providing full template instances (and not just template names) in the `layout` and/or `template` parameters. And since there might be several templates rendered simultaneously, maybe let the 'template' contain multiple templates?

For example what I do now:
```
// routes.js
import { LayoutWebsite } from '/imports/ui/layouts/website';
import { ApiWebsiteLanding } from '/imports/api/website/landing';

...

landingPage.route('/', {
  name: 'landing',
  action(params, queryParams) {
    BlazeLayout.render(LayoutWebsite, {
      ComponentDynamic: ApiWebsiteLanding,
    });
  }
});
```

```
// website.html
<component name='LayoutWebsite'>
  <div id='layouts-website'>
    {{> SomeHeader}}
    <div id='content' >
      {{> ComponentDynamic}}
    </div>
    {{> SomeFooter}}
  </div>
</component>

```

For this to work I have hacked a bit blaze-layout, but it could be great if someone with more experience with flow-router and blaze-layout could do this properly.

**Comment by dr-dimitru** [comment]
Actually same hack should work with current `this.render()` method:

```html
<!-- layout.html -->
<template name="layout">
  {{> yield}}
</template>
```

```html
<!-- component.html -->
<template name="component">
  {{> Template.dynamic template=component}}
</template>
```

```js
// routes.js
landingPage.route('/', {
  name: 'landing',
  action(params, queryParams) {
    this.render('layout', 'component', {
      component: ApiWebsiteLanding
    });
  }
});
```

As I understood if it will be possible to change template names to actual *Template* instances, it will solve your suggestion, right?

**Comment by dr-dimitru** [comment]
BTW https://github.com/nathantreid/blaze-modules project seems to be stale now, last update more than 6 month ago, may be it's better to wait for `meteor@1.5`?

And of course we can add possibility to pass *Template* instances instead of names.
`meteor@1.5` should bring similar approach of importing `*.html` files as *Template* instances

**Comment by vbgm** [comment]
In your example the 'layout' still seem to be a template name, not instance. And in my example the LayoutWebsite is template instance.

> As I understood if it will be possible to change template names to actual Template instances, it will solve your suggestion, right?

Exactly, however there are couple of places in my app where I load several templates at once based on route, thus, thinking if {{> yield}} and this.render() single template is enough.. any chances to render multiple? The BlazeLayout second parameter is object and (after a hack) allows you to actually pass any parameter (including as many template instances as you want) right into the layout template. Thus, allowing Template.dynamic functionality with locally scoped templates.

> BTW https://github.com/nathantreid/blaze-modules project seems to be stale now, last update more than 6 month ago, may be it's better to wait for meteor@1.5?

I would say it is still new and not many people know about it. From what I read from here [https://github.com/meteor/blaze/issues/15](https://github.com/meteor/blaze/issues/15) it might eventually become de-facto blaze componentization approach. And from what I see and read here: [https://blog.meteor.com/dynamic-imports-in-meteor-1-5-c6130419c3cd#.wbekoaloq]() and on the forum, meteor 1.5 won't bother with blaze directly, instead it will just provide a mechanism of lazy loading any files, be it Blaze, React or anything else.

**Comment by dr-dimitru** [comment]
> In your example the 'layout' still seem to be a template name, not instance. And in my example the LayoutWebsite is template instance.

Right, I've just said what you can use similar hack with current implementation.

> any chances to render multiple?

Why not? Third argument of `this.render()` will accept *Object* with any values and pass it right to the template.

> 1.5 won't bother with blaze directly, instead it will just provide a mechanism of lazy loading any files

Right, but including `.html`/`.jade` files will return *Template* instance, which will allow to pass it to the `.render()`

> I would say it is still new and not many people know about it. From what I read from here meteor/blaze#15 it might eventually become de-facto blaze componentization approach.

Well... we will see


Anyways I'll add support for passing *Template* instances instead of its names

**Comment by vbgm** [comment]
Thanks.
> Third argument of this.render() will accept Object with any values and pass it right to the template.

Then there is a question on why to have {{yield}} at all? :-)

**Comment by vbgm** [comment]
> but including .html/.jade files will return Template instance, which will allow to pass it to the .render()

If it is the case, then it will actually behave exactly as blaze-modules. Have you seen any roadmap on when this might be implemented?

**Comment by dr-dimitru** [comment]
> Then there is a question on why to have {{yield}} at all? :-)

 1. Simplification - usually there is one template per layout, other things like sidebar or footer is static dependencies
 2. Speed - We have optimized rendering and reactive re-rendering, with best JS/HTML practices. Other regions won't be optimized

> Have you seen any roadmap on when this might be implemented?

No, only this thread:
https://forums.meteor.com/t/what-is-import-of-html-file/20431

**Comment by vbgm** [comment]
Okay, so blaze-modules is essentially the realisation of this importing template instance.

> Other regions won't be optimised

That's a pity then. My app layout for example always uses minimum 3 dynamic templates that are loaded based on queryParams.. :-/ Imagine a list of items and a selected item details, like in a typical mail app.. there are at least 2 templates. So it looks a bit strange compared to BlazeLayout for example, where there is layout and then there is set of dynamic templates..

**Comment by dr-dimitru** [comment]
BlazeLayout doesn't have such optimization either. Moreover `BlazeLayout` is stale.
Check its sources, they are using a lot of hacks due to old Blaze limitations.

Anyways don't take my word for it, use "Timeline" in devtools to understand how templates is rendered, and what blocks UI and drops FPS.

`.render()` method was implemented as I wasn't able to provide smooth UI for website with a lot of animations.

**Comment by vbgm** [comment]
Thanks for the explanation then.

**Comment by dr-dimitru** [comment]
You may try to create new instance of [`BlazeRenderer`](https://github.com/VeliovGroup/flow-router/blob/master/client/renderer.js#L10) passing *Function* which returns root DOM element to constructor.

So if you have a 3-column layout:
```html
<body>
  <div id="col1"></div>
  <div id="col2"></div>
  <div id="col3"></div>
</body>
```

```js
import { BlazeRenderer } from 'meteor/ostrio:flow-router-extra';

const col1 = new BlazeRenderer(() => {
  return document.getElementById('col1');
});

const col2 = new BlazeRenderer(() => {
  return document.getElementById('col2');
});

const col3 = new BlazeRenderer(() => {
  return document.getElementById('col3');
});
```

Then in routes:
```js
landingPage.route('/', {
  name: 'landing',
  action(params, queryParams) {
    col1.render('column1', 'template');
    col2.render('column2', 'template');
    col3.render('column3', 'template');
  }
});
```

**Comment by dr-dimitru** [comment]
The key thing here is independent re-rendering of each instance

**Comment by vbgm** [comment]
Might be an option, will need to try in a while. Thank you.

**Comment by vbgm** [comment]
I am working on this now, and have few questions right away. Was there a specific reason in using render() method vs the ordinary Blaze 'Template.dynamic'? Or Template.dynamic is not optimised as well? :-/

**Comment by dr-dimitru** [comment]
Yes, pass data from route to the template:

```js
FlowRouter.route('/post/:_id', {
  name: 'post',
  action(params, queryParams, post) {
    this.render('_layout', 'post', {post: post});
  },
  waitOn(params) {
    return [Meteor.subscribe('post', params._id)];
  },
  data(params, queryParams) {
    return PostsCollection.findOne({_id: params._id});
  }
});
```

**Comment by dr-dimitru** [comment]
Hello @vblagomir ,

Partially implemented in https://github.com/VeliovGroup/flow-router/commit/33516c663a2a98de852c39825962ce15a9750087

Let me know if it's what you're looking for

**Comment by dr-dimitru** [comment]
@vblagomir published as [v3.1.1](https://github.com/VeliovGroup/flow-router/releases/tag/3.1.1)

Let me know if it works for you.

**Comment by dr-dimitru** [comment]
Hello @vblagomir ,

Did you get a chance to test it?

**Comment by vbgm** [comment]
Hi @dr-dimitru, sorry I won't be able to test it at the moment. Been too busy. Will check once get a bit more free.

**Comment by dr-dimitru** [comment]
@vblagomir sure, no worries, just keep this thread updated.

**Comment by dr-dimitru** [comment]
Hello @vblagomir ,

Any news on your end?

**Comment by vbgm** [comment]
I have updated to 1.5.1 and informed a developer of blaze-modules about update (as there are some conflicts yet). Once that is done I will gladly test this, as for the new project I have selected flow-router-extra. Please do not close this for now.

**Comment by dr-dimitru** [comment]
@vblagomir thank you for update.

**Comment by dr-dimitru** [comment]
Hello @vblagomir , any updates on this one?

**Comment by vbgm** [comment]
@dr-dimitru we might close this for now and when I check it I could reopen when I come back to the project I worked on.

**Comment by dr-dimitru** [comment]
TBD
