### ISSUE TITLE
Contributor wanted

### ISSUE THREAD

**Issue by dr-dimitru** [VeliovGroup/flow-router#64]
Hello developer, yes I'm talking to you. Want to join the decentralized web development team of the future as a open source contributor? Get a chance to contribute to the packages used by hundreds and thousands of other developers around the globe?

I thought so too. Tell us what you've already accomplished and what your goals are, send your skills and story to 942d258a4297ce9d438ce3f1fe97e4fe518440c9.

All question are welcome here.

_yes, it's a small quiz to solve_

**Comment by channasmcs** [comment]
what is require skill looking for ?

**Comment by dr-dimitru** [comment]
@channasmcs 

1. Open source repository and community management;
2. Documentation writing skills and English writing skills for that matter;
3. JavaScript, Meteor, Node.js, MongoDB.

And you need to pass quiz from my OP

**Comment by thearabbit** [comment]
I want too, But my English is not native!

**Comment by dr-dimitru** [comment]
@thearabbit It's very easy to start with taking over one of the open issues.
Here's one long-going discussion — https://github.com/VeliovGroup/flow-router/issues/66
