### ISSUE TITLE
Is it possible to update params / queryParams without re-rendering?

### ISSUE THREAD

**Issue by jankapunkt** [VeliovGroup/flow-router#70]
- Give an expressive description of what is went wrong

I have the issue, that I want to update my params or query params without rendering again, which causes all content to be redrawn and thus disappear for a slight moment. Others might think this is a glitch or something.

Is this intended behavior (reactivity)? Can I prevent it?

Note: I am not sure how far this is related to #66 because I have not a real "error" and I think it is not.

  - Version of `flow-router-extra` you're experiencing this issue
3.6.3

  - Version of `Meteor` you're experiencing this issue
1.8.1

  - Browser name and its version (Chrome, Firefox, Safari, etc.)?
All

  - Platform name and its version (Win, Mac, Linux)?
All

**Comment by dr-dimitru** [comment]
@jankapunkt need route definition example. From your description, I'd say it caused by `waitOn`, `data` or other hook as it must re-run in order to pull fresh data (e.g. URL/route is changed, all hooks must re-run)

**Comment by dr-dimitru** [comment]
@jankapunkt see [this updated docs](https://github.com/VeliovGroup/flow-router/blob/master/docs/templating.md#force-template-re-rendering), by default if you aren't rendering other templates in `waitOn`/`whileWaiting` and other router's hooks, __and using layout__ with `{{> yield}}` template won't be re-rendered upon params/URI change.

**Comment by jankapunkt** [comment]
Thank you, works great! I close the issue as it's resolved.
