### ISSUE TITLE
Could I use `Helpers` in React?

### ISSUE THREAD

**Issue by thearabbit** [VeliovGroup/flow-router#71]
Could I use `Helpers` in React?
Please example

**Comment by dr-dimitru** [comment]
Hello @thearabbit ,

Yes, `RouteHelpers` can be imported and used directly, read more in the docs — https://github.com/VeliovGroup/flow-router/blob/master/docs/helpers/RouterHelpers.md


Feel free to close it in case if the issue is solved on your end.

**Comment by dr-dimitru** [comment]
@thearabbit full list of available *Client* helpers can be [found here](https://github.com/VeliovGroup/flow-router/blob/master/client/active.route.js#L289)

**Comment by thearabbit** [comment]
Very quick reply, thanks 💯
