### ISSUE TITLE
Sample projects in `Meteor + React + FlowRouter`?

### ISSUE THREAD

**Issue by thearabbit** [VeliovGroup/flow-router#72]
Could you share sample projects in `Meteor + React + FlowRouter`?

**Comment by dr-dimitru** [comment]
@thearabbit I’d ask on forums.meteor.com

**Comment by dr-dimitru** [comment]
@thearabbit also see [other issues marked with *React* label](https://github.com/VeliovGroup/flow-router/issues?utf8=✓&q=is%3Aissue+label%3Areact+)

**Comment by thearabbit** [comment]
Ok, thanks again 👍
