### ISSUE TITLE
Force `Router.update()`

### ISSUE THREAD

**Issue by MaxmaxmaximusGitHub** [VeliovGroup/flow-router#76]
I added a route 1 second after loading the page, how can I call the method. `Router.update ()` so that it checks for which route the current ur is suitable for?

**Comment by MaxmaxmaximusGitHub** [comment]
solution:

```javascript
FlowRouter.wait();
WhenEverYourAppIsReady(() => {
  FlowRouter.initialize();
});
```

**Comment by MaxmaxmaximusGitHub** [comment]
it doesn't suit me:
```javascript
FlowRouter.wait();
WhenEverYourAppIsReady(() => {
  FlowRouter.initialize();
});
```

i need like this
```coffeescript
	add: (page)->
		@pages.push(page)
		
		FlowRouter.route page.href,
			name  : page.name,
			action: => @activate(page)

		FlowRouter.update() # i need like this
		return
```

**Comment by dr-dimitru** [comment]
@MaxmaxmaximusGitHub thank you for this suggestion.
Adding a feature to initialize routes on the fly (during runtime) will require major changes.
As right now we have stable and old codebase inherited from original package with many flaws, I'm keeping this feature open for next major v4 release

**Comment by dr-dimitru** [comment]
@MaxmaxmaximusGitHub looks like there's actually a trick to pull new routes dynamically, and it was [used in our tests for a long time](https://github.com/veliovgroup/flow-router/blob/master/test/client/router.core.spec.js#L745)

After new routes passed into `FlowRouter.route()` method:

```js
const reloadRoutes = () => {
  FlowRouter._initialized = false;
  FlowRouter.initialize();
}
```

**Comment by dr-dimitru** [comment]
Trick from [comment above](https://github.com/veliovgroup/flow-router/issues/76#issuecomment-1161917201) should sole this issue

@MaxmaxmaximusGitHub Feel free to reopen it in case if the issue is still persists on your end.
