### ISSUE TITLE
Question: Function to get all routes

### ISSUE THREAD

**Issue by jaybeemind** [VeliovGroup/flow-router#81]
Does FlowRouter have a function that returns all routes?
Use case is for setting roles/permission per route name in admin panel.

Thanks in advance.

**Comment by dr-dimitru** [comment]
`FlowRouter` is singleton and it should be storing all routes map, just expose FlowRouter and `console.log` it.
It isn't part of official JS API, so please, after finding an answer — update this thread with solution, perhaps someone else was looking for routes map

**Comment by jaybeemind** [comment]
Found it using this: `console.log('Routes:', FlowRouter._routes)`.
Thanks!
