### ISSUE TITLE
Going to localhost:3000/packages/jquery.js displays a file

### ISSUE THREAD

**Issue by nikhilgoswami** [VeliovGroup/flow-router#82]
### I'm having an issue:
  I don't know the issue is related to this package but on meteor project going to localhost:3000/packages/jquery.js displays a file.
  - Version of `Meteor`  1.10.2
  - Browser name and its version all
  - Platform name and its version  Ubuntu not tested others
test url  https://vapt.ecobillz.com/app/packages/jquery.js

### I have a suggestion:

Disable source map access through routes

**Comment by dr-dimitru** [comment]
Hello @nikhilgoswami,

This is beyond this package as served by meteor's static assets middleware (e.g. serve route).
And browsers need to get those files  via HTTP as well, so there's no need to disable it

**Comment by nikhilgoswami** [comment]
Okay thanks for your help
