### ISSUE TITLE
this.render regions reloading whole page

### ISSUE THREAD

**Issue by CyberCyclone** [VeliovGroup/flow-router#85]
### I'm having an issue:
  - Version: 3.7.5
  - Version of `Meteor`: 1.11.1
  - Browser name and its version: Chrome, Firefox
  - Platform name and its version: Mac, iOS

I'm having an issue where all regions are reloading even though the parent region shouldn't change. Using the below code renders the Layout_body and region 'Page_home' correctly.

```
FlowRouter.route('/', {
	name: 'index',
	action() {
		// Render a template using Blaze
		this.render('Layout_body', {main: 'Page_home'});
	}
});
```

I then have this code and if I change routes (`<a href="/faq">FAQ</a>`), both the Layout_body and Page_faq load. As in, the Layout_body gets reloaded as well. I've added a console.log to the onCreated and onRendered for Layout_body and it's printing out on every layout change, when it should only be running once on the initial load.
```
FlowRouter.route('/faq', {
	name: 'frequently asked questions',
	action() {
		// Render a template using Blaze
		this.render('Layout_body', {main: 'Page_faq'});
	}
});
```

As far as I know this isn't meant to be by design and Layout_body should have only run once.

Thanks!

**Comment by dr-dimitru** [comment]
Hello @CyberCyclone,

Please read [`.render()` method](https://github.com/VeliovGroup/flow-router/blob/master/docs/api/render.md) documentation. When passing only single template name it is treated as a Template not a Layout.

Feel free to close it in case if the issue is solved on your end.

**Comment by CyberCyclone** [comment]
From the documentation I interpreted `this.render('Layout_body');` to be a template and `this.render('Layout_body', {main: 'Page_home'});` to be a layout with template regions.

Using `this.render('Layout_body', 'Page_home');` works as you said.

**Comment by dr-dimitru** [comment]
@CyberCyclone great! I'm glad this was quickly solved :) 

-----

Please support this project with:
 - [Become a sponsor on GitHub](https://github.com/sponsors/dr-dimitru) and GitHub __would double your every contribution__ in next 12 months!;
 - Support [via PayPal](https://paypal.me/veliovgroup);
 - Star this package on GitHub;
 - Like [at Facebook](https://www.facebook.com/veliovgroup);
 - Follow [on Twitter](https://twitter.com/veliovgroup);
 - Check and star our [other open source projects on GitHub](https://github.com/VeliovGroup).
