### ISSUE TITLE
Malformed URI! /login?target=%2F TypeError: Cannot read property 'document' of undefined

### ISSUE THREAD

**Issue by crapthings** [VeliovGroup/flow-router#87]
what can cause this error?

Malformed URI! /login?target=%2F TypeError: Cannot read property 'document' of undefined

**Comment by dr-dimitru** [comment]
@crapthings You haven't provided much details — https://github.com/veliovgroup/flow-router/blob/master/client/router.js#L288
Hope that helps. I think `document` might not be found on a Server? Where do you get this error?

**Comment by crapthings** [comment]
codebase kind of large, i just drop-in replace the old one
maybe some server side code import shared module
let me check first

**Comment by crapthings** [comment]
i've found this issue not just caused by flow-router but page.js

test with parcel.js and page.js same issue

![image](https://user-images.githubusercontent.com/1147704/115358432-3a768180-a1f0-11eb-927a-5c23e7551fd5.png)

![image](https://user-images.githubusercontent.com/1147704/115358518-567a2300-a1f0-11eb-9c71-fbeae17b2b73.png)


```
page('/about', function () {
  console.log(1123123)
})

page('/', function () {
  console.log(1123123)
})
```

**Comment by dr-dimitru** [comment]
@crapthings page.js cause a lot of pain lately, and we are not able to upgrade it to the latest release either — tests won't pass.
I'm having in plans a major release completely rewriting FlowRouter as it is bulky and got complex so far. But it would require a lot if time, it's just waiting for my free time 😅

**Comment by crapthings** [comment]
yeah a meteor tracker aware client router like flow router is very good, we can use this work with any front ui framework.
