### ISSUE TITLE
add Route Changing reactive source?

### ISSUE THREAD

**Issue by crapthings** [VeliovGroup/flow-router#88]
do we have such status, so we can check this status to prevent watching further watchpathchange reactive source that call react setState?

when u work with ui framework like react, you build a tracker container no matter a react class componet or functional component with useeffect hook, you start a tracker in it and you track flowrouter's reactive source like watchpathchange, getparams etc, then after you invoke flowrouter.go, this will lead container's tracker rerun  Immediately then call react setState, but meanwhile this container will recieve undefine props from route state and pass down to child component will cause crash before next flowrouter's action call a reactdom.render.

i will post a repo to reproduce.

and wonder how people solve such problem in normal?

**Comment by crapthings** [comment]
```
useEffect(function () {
  const comp = Tracker.autorun(function () {
    const keyword = flowrouter.getQuery('keyword')
if (!keyword) return // i want to replace here to watch if route is not changing
   setState(keyword)
  })

  return function () {
    comp?.stop()
  }
}, [])
```

**Comment by dr-dimitru** [comment]
Hello @crapthings,

It's solved either with wrapping reactive code into `Tracker.nonreactive` or accessing non-reactive state `FlowRouter._current.route`. And checking if state returns undefined props to avoid any further action.

Maybe @afrokick can tell you more, I know they are using FR  with react a lot

**Comment by afrokick** [comment]
Yeah, we had the same issue. We decided to use Tracker.nonreactive.

```javascript
//our custom hook
const useParam = pName => Tracker.nonreactive(() => FlowRouter.getParam(pName));

function MyPage() {
   const someNonReactiveParam = useParam('p');

  ...
}
```

If we want to handle params changes, just pass it to component via route definition in action function. Another solution to use custom hook like useReactiveParam.

```javascript
function MyPage2({ someReactiveParam }) {
  ...
}

FlowRouter.route('/somepath', {
  action({ pName }) {
    render(<MyPage2 someReactiveParam={pName}/>);
  },

```

**Comment by crapthings** [comment]
https://github.com/crapthings/fr88

![image](https://user-images.githubusercontent.com/1147704/117746942-df104000-b23f-11eb-927e-682d4ae449c0.png)

```
{path: "/", params: {…}, route: Route, context: Context, oldRoute: Route, …} undefined
page2 unmount
home mount
{path: "/", params: {…}, route: Route, context: Context, oldRoute: Route, …} undefined
```

i'm about to leave page2 to the home page, and you can see that an tracker rerun happend and it tracks the next route state.


yes i do use pass props to react component, but what i try to achieve is something like

![image](https://user-images.githubusercontent.com/1147704/117749569-9444f700-b244-11eb-9530-15f0c1e98749.png)


the container don't use react context to pass down deep props, it accesses route state directly with tracker

**Comment by crapthings** [comment]
something like this

```
export default function () {
  useEffect(function () {
    console.log('page2 mount')
    const trackerHandler = Tracker.autorun(function () {
      if (FlowRouter.changingRoute()) return
      console.log(FlowRouter.current(), FlowRouter.getQueryParam('something'))
    })

    return function () {
      console.log('page2 unmount')
      trackerHandler?.stop()
    }
  }, [])
  return (
    <div>page2</div>
  )
}
```


meteor account has such reactive source that know a state of login

https://docs.meteor.com/api/accounts.html#Meteor-loggingIn

**Comment by afrokick** [comment]
```javascript
export default function () {
  useEffect(function () {
    console.log('home mount')
    const trackerHandler = Tracker.nonreactive(function () {
      console.log(FlowRouter.current(), FlowRouter.getQueryParam('something'))
    })

    return function () {
      console.log('home unmount')
      trackerHandler?.stop()
    }
  }, [])
  return (
    <div>home</div>
  )
}
```

**Comment by crapthings** [comment]
@afrokick

```
FlowRouter.setQueryParams({ something: 111111 })
FlowRouter.go('/page1?something=111111122222')
```

but these methods will failed if we stay same page

**Comment by crapthings** [comment]
it looks useLayoutEffect works

```js
export default function () {
  // const mounted = useRef(false)

  useLayoutEffect(function () {
    console.log('page1 mount')
    const trackerHandler = Tracker.nonreactive(function () {
      return Tracker.autorun(function () {
        // if (mounted.current === false) return
        console.log('page1 inside tracker', FlowRouter._current, FlowRouter.getQueryParam('something'))
      })
    })

    return function () {
      // mounted.current = false
      console.log('page1 unmount')
      trackerHandler?.stop()
    }
  }, [])

  return (
    <div>page1</div>
  )
}
```

**Comment by afrokick** [comment]
If you want to handle query changes, use action params:

```javascript
export default function (props) {
  console.log(`props:`, props);

  useEffect(function () {
    console.log('page1 mount')

    return function () {
      console.log('page1 unmount')
    }
  }, [])
  return (
    <div>page1</div>
  )
}

FlowRouter.route('/page1', {
  action (_,q) {
    render(<Layout><Page1 something={q.something} /></Layout>, ReactRoot)
  }
})
```

**Comment by crapthings** [comment]
@afrokick  i do use these in some case, but what i want is i don't use props pass down, or react createContext provider, i want to use Meteor's reactive source, and make an react wrapper component to subscribe state from reactive dict, var, minimongo etc...

thanks useLayoutEffect works like componentDidMount after i read react document again. 

the issue only happen in hook component.
