### ISSUE TITLE
Autoscroll Functionality

### ISSUE THREAD

**Issue by ajschmaltz** [VeliovGroup/flow-router#9]
For some reason https://github.com/okgrow/router-autoscroll doesn't work with this package.  Any suggestions on how to revive this functionality?

**Comment by dr-dimitru** [comment]
Hello @ajschmaltz ,

A quick look on [router-autoscroll repository](https://github.com/okgrow/router-autoscroll) reveals it's being deprecated:

> __[DEPRECATED]__ Smart management of scroll position across route changes for iron and flow router

And it [has dependency](https://github.com/okgrow/router-autoscroll/blob/master/package.js#L15) of original FR package.

But the good news are here - you can implement it easily:
```jsx
import { FlowRouter } from 'meteor/ostrio:flow-router-extra';

const scrollToTop = () => {
  setTimeout(() => {
    if (!window.location.hash) {
      window.scroll(0, 0);
    }
  }, 25);
};

FlowRouter.triggers.enter([scrollToTop]);
```

Let me know if it works for you.

**Comment by dr-dimitru** [comment]
@ajschmaltz did you got a chance to implement it?

**Comment by tmpg** [comment]
Can this be built into the package? I can't seem to get this to work. Does it go on each route?

**Comment by dr-dimitru** [comment]
@tmpg 

> Does it go on each route?

Yes, `FlowRouter.triggers` registers global trigger and applied to each registered route.

> I can't seem to get this to work.

Do you got any errors? Can you add `.log` to see if it's triggered

> Can this be built into the package?

Looks overwhelming to me, as it can be done with few lines in a global trigger.
Let's see if it will get up votes by community.

**Comment by coagmano** [comment]
Looking at [okgrow/router-autoscroll](/okgrow/router-autoscroll), it should work perfectly fine. Just [follow the instructions here](https://github.com/VeliovGroup/flow-router#other-packages-compatibility) for compatibility with packages that rely on the original FlowRouter

Even if you don't want to use the package, it's not hard to add to your project with a single global trigger. So I don't see any reason it should be part of the package

**Comment by dr-dimitru** [comment]
@coagmano well, autoscroll package has [dependency](https://github.com/okgrow/router-autoscroll/blob/master/package.js#L15) of original FlowRouter. Having two packages won't harm your app, but wouldn't be good either. May cause conflicts and increase application size.

**Comment by coagmano** [comment]
It's a weak dependency, so it won't install automatically. By setting `Package['kadira:flow-router'] = Package['ostrio:flow-router-extra'];` before it loads, it will use this FlowRouter instead of the original

**Comment by dr-dimitru** [comment]
@coagmano you right, haven't noticed `{weak: true}`, my bad.
Anyways, this is just 8 lines:
```js
const scrollToTop = () => {
  setTimeout(() => {
    if (!window.location.hash) {
      window.scroll(0, 0);
    }
  }, 25);
};

FlowRouter.triggers.enter([scrollToTop]);
```

**Comment by dr-dimitru** [comment]
Shall we move it to the docs and close the ticket?
@ajschmaltz @coagmano @mksh-su @tmpg

**Comment by dr-dimitru** [comment]
[Added to docs](https://github.com/VeliovGroup/flow-router/blob/master/docs/auto-scroll.md)
