### ISSUE TITLE
go() query string repetition bug

### ISSUE THREAD

**Issue by drone1** [VeliovGroup/flow-router#93]
### I'm having an issue:
  - Give an expressive description of what is went wrong
  > Before I realized I can just call FlowRouter.setQueryParam(), I was running code that repeatedly (in my case, each time I would click a button), results in the query string param 'test' being repeated on the URL:

```
const route = FlowRouter.current()
const qs = {...route.queryParams} // clone
qs.test = 1
FlowRouter.go(
    route.path,
    {...route.params},	// clone
    qs
)
```
Shouldn't this be like calling setQueryParam()? Instead it results in the current path etc but adds ``?test=1?test=1?test=1...`` to the URL. I would expect ``/path?test=1``

  - Version of `flow-router-extra` you're experiencing this issue
  > 3.7.5
  - Version of `Meteor` you're experiencing this issue
  > 2.0
  - Browser name and its version (Chrome, Firefox, Safari, etc.)?
  > Chrome Version 96.0.4664.110 (Official Build) (64-bit)
  - Platform name and its version (Win, Mac, Linux)?
  Windows 10 20H2

**Comment by zeearth** [comment]
@dr-dimitru hi, your commit generate a bug we have more than one parameter optional into pathDef.
Our pathdef : '/companies/:id?/:action?/'
When we call the path method : FlowRouter.path('companies', { id: this._id._str, action: mode })
the generated path is no more correct : "/companies/6135cb32d14df059605901fd?%2F%3Aaction="

in 3.7.5 of the package the generated path is like this : "/companies/6135cb32d14df059605901fd/edit"

thanks for you return

**Comment by dr-dimitru** [comment]
Hello @zeearth thank you for reporting.

This case is [part of the tests](https://github.com/veliovgroup/flow-router/blob/master/test/common/router.path.spec.js#L96).

Can you post values of `console.log({id: this._id._str, action: mode})` looking ant the generated path `mode` is null or empty string?

**Comment by zeearth** [comment]
Hello @dr-dimitru 

I saw your test, but my parameters are optionnal. I'm thinking problems come from the split on the '?'  [router.js:226](https://github.com/veliovgroup/flow-router/blob/b7407b07ae7a3f61fedb7a25f11aa317eb240017/client/router.js#L226)  I think the split is done for separate uri and query string. 
this._id._str is a common mongodb id string "629f87f44ec0e563c4d5c458" mode is a string view or edit.

**Comment by dr-dimitru** [comment]
@zeearth seems like I finally caught this one, try running on updated [`v3.8.1`](https://github.com/veliovgroup/flow-router/releases/tag/3.8.1). lmk

**Comment by zeearth** [comment]
Good for us @dr-dimitru.
Thanks for the quick buck fix and for all you work.
