### ISSUE TITLE
Errors in types.d.ts

### ISSUE THREAD

**Issue by perbergland** [VeliovGroup/flow-router#97]
### I'm having an issue:
  - Give an expressive description of what is went wrong
The types.d.ts file does not compile after having zodern:types place it in .meteor/local/types

.meteor/local/types/node_modules/package-types/ostrio_flow-router-extra/package/web.cordova/types.d.ts (5,62): String literal expected.
.meteor/local/types/node_modules/package-types/ostrio_flow-router-extra/package/web.cordova/types.d.ts (16,7): Cannot find namespace 'Meteor'.
.meteor/local/types/node_modules/package-types/ostrio_flow-router-extra/package/web.cordova/types.d.ts (17,7): Cannot find namespace 'Tracker'.
.meteor/local/types/node_modules/package-types/ostrio_flow-router-extra/package/web.cordova/types.d.ts (18,13): Cannot find namespace 'Tracker'.
.meteor/local/types/node_modules/package-types/ostrio_flow-router-extra/package/web.cordova/types.d.ts (20,37): Cannot find namespace 'Meteor'.
.meteor/local/types/node_modules/package-types/ostrio_flow-router-extra/package/web.cordova/types.d.ts (30,48): Cannot find namespace 'Mongo'.

  - Version of `flow-router-extra` you're experiencing this issue
 3.9.0

This line is syntactically incorrect:

```typescript
type DynamicImport<T extends string> = Promise<typeof import(T)>;
```

Metor, Tracker and Mongo packages need to be imported

Here are manual modifications that make the compilation errors go away but the DynamicImport type function can probably not be implemented at all.

```typescript
import { Meteor } from "meteor/meteor";
import { Mongo } from "meteor/mongo";
import { Tracker } from "meteor/tracker";

type Trigger = (context: ReturnType<Router["current"]>, redirect: Router["go"], stop: () => void, data: any) => void;

type TriggerFilterParam = { only: string[] } | { except: string[] };

// @ts-ignore
type DynamicImport<T extends string> = Promise<typeof import(T)>;

```

**Comment by dr-dimitru** [comment]
@perbergland would it get solved by adding Tracker and Mongo as `{weak: true}` dependencies?

**Comment by dr-dimitru** [comment]
@timsun28 would you be able to help with this one?

**Comment by timsun28** [comment]
I believe I have solved both issues in this [pr](https://github.com/veliovgroup/flow-router/pull/99). 
I have added meteor types to flowrouter so they can be imported and it now recognizes them when using the package.
I have also changed the DynamicImport to now only accept a string and solved the issue it was initially giving.

I hope this helps your problems!

**Comment by dr-dimitru** [comment]
@timsun28 @perbergland I left [a comment](https://github.com/veliovgroup/flow-router/pull/99#issuecomment-1497255939) in the PR

**Comment by dr-dimitru** [comment]
Should be solved in the latest release
Feel free to reopen it in case if the issue is still persists on your end.
